
trigger:
- master

pool:
  name: Default
  demands: maven

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'DevOpsDemo/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: 'DevOpsDemo'
    Contents: '''**\DevOpsDemo\*'''
    ArtifactName: 'drop'
    ArtifactType: 'FilePath'
    TargetPath: '\\localhost\NewBuildDropLocation\$(Build.DefinitionName)\$(Build.BuildNumber)'

